#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM <?php printf("php:%s-%s\n", $phpVersion, $flavour) ?>

MAINTAINER AndriynomeD <andriynomed.work@gmail.com>

###########################################################################
# Install dependencies
###########################################################################
<?php
    $imagePackages = array_merge([
        'libfreetype6-dev',
        'libicu-dev',
        'libjpeg62-turbo-dev',
        'libmcrypt-dev',
        'libpng-dev',
        'libxslt1-dev',
        'libzip-dev',
        'zip',
        'unzip',
        'sudo',
        'git'
    ], $packages ?? [], $flavourPackages ?? [])
?>

RUN apt-get update \
  && apt-get install -y \
    <?php echo join(" \\ \n    ", $imagePackages) ?> \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*


###########################################################################
# Install required PHP extensions
###########################################################################
<?php $imagePhpExtensions = array_merge([
  'dom',
  'intl',
  'mbstring',
  'pdo_mysql',
  'xsl',
  'soap',
  'bcmath',
  'pcntl',
  'sockets'
], $phpExtensions ?? [], $flavourPhpExtensions ?? []);
?>

RUN docker-php-ext-install -j$(nproc) \
  <?php echo join(" \\ \n  ", $imagePhpExtensions) ?>


<?php include "Docker-specific-packages"; ?>

###########################################################################
# Configuring...
###########################################################################

ENV PHP_MEMORY_LIMIT=2G \
    PHP_ENABLE_XDEBUG=false \
    MCS_ROOT=/var/www/magento-coding-standard \
    DEBUG=false \
    UPDATE_UID_GID=false

COPY docker-entrypoint-mcs.sh /docker-entrypoint.sh
RUN ["chmod", "+x", "/docker-entrypoint.sh"]

ENTRYPOINT ["/docker-entrypoint.sh"]
