#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM <?php printf("php:%s-%s\n", $phpVersion, $flavour) ?>

MAINTAINER AndriynomeD <andriynomed.work@gmail.com>

###########################################################################
# Install dependencies
###########################################################################
<?php
    $imagePackages = array_merge([
        'libfreetype6-dev',
        'libicu-dev',
        'libjpeg62-turbo-dev',
        'libmcrypt-dev',
        'libpng-dev',
        'libxslt1-dev',
        'libzip-dev',
        'sudo',
        'git'
    ], $packages ?? [], $flavourPackages ?? [])
?>

RUN apt-get update \
  && apt-get install -y \
    <?php echo join(" \\ \n    ", $imagePackages) ?>


###########################################################################
# Install required PHP extensions
###########################################################################
<?php $imagePhpExtensions = array_merge([
  'dom',
  'intl',
  'mbstring',
  'pdo_mysql',
  'xsl',
  'zip',
  'soap',
  'bcmath',
  'pcntl',
  'sockets'
], $phpExtensions ?? [], $flavourPhpExtensions ?? []);
?>

RUN docker-php-ext-install \
  <?php echo join(" \\ \n  ", $imagePhpExtensions) ?>


<?php include "Docker-specific-packages"; ?>

###########################################################################
# Configuring...
###########################################################################

ENV PHP_MEMORY_LIMIT 2G
ENV PHP_ENABLE_XDEBUG false
ENV MCS_ROOT /var/www/magento-coding-standard

ENV DEBUG false
ENV UPDATE_UID_GID false

ADD docker-entrypoint-mcs.sh /docker-entrypoint.sh

RUN ["chmod", "+x", "/docker-entrypoint.sh"]

ENTRYPOINT ["/docker-entrypoint.sh"]
