#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM php:{{ phpVersion }}-{{ flavour }}

LABEL maintainer="AndriynomeD <andriynomed.work@gmail.com>"

{% set parts = phpVersion|split('.') %}
{% set shortVersion = parts[0] ~ '.' ~ parts[1] %}
ARG PHP_VERSION={{ shortVersion }}

###########################################################################
# Install dependencies
###########################################################################
{% set imagePackages = [
    'libicu-dev',
    'libfreetype6-dev',
    'libjpeg62-turbo-dev',
    'libpng-dev',
    'libmcrypt-dev',
    'libxslt1-dev',
    'libzip-dev',
    'sudo',
    'git'
]|merge(packages|default([]))|merge(flavourPackages|default([])) %}

RUN apt-get update \
  && apt-get install -y \
    {{ imagePackages|join(' \\\n    ') }} \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

###########################################################################
# Install required PHP extensions
###########################################################################
{% set imagePhpExtensions = [
  'dom',
  'intl',
  'mbstring',
  'pdo_mysql',
  'xsl',
  'soap',
  'bcmath',
  'pcntl',
  'sockets'
]|merge(phpExtensions|default([]))|merge(flavourPhpExtensions|default([])) %}

RUN docker-php-ext-install -j$(nproc) \
  {{ imagePhpExtensions|join(' \\\n  ') }} \
    && docker-php-source delete

###########################################################################
# Zip/Unzip (copy from https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile):
###########################################################################

RUN apt-get update \
  && apt-get install -y \
    libzip-dev zip unzip && \
    if [ ${PHP_VERSION} = "7.3" ] || [ ${PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
      docker-php-ext-configure zip; \
    else \
      docker-php-ext-configure zip --with-libzip; \
    fi && \
    # Install the zip extension
    docker-php-ext-install zip && \
    php -m | grep -q 'zip' \
    && docker-php-source delete \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

{% include "phpContainers/includes/specific-packages.twig" %}
###########################################################################
# Install Xdebug (but don't enable)
###########################################################################

{% set xdebugVersionFlag = (xdebugVersion == 'latest' or xdebugVersion == '') ? '' : '-' ~ xdebugVersion %}
RUN pecl install -o -f xdebug{{ xdebugVersionFlag }} && rm -rf /tmp/pear
ADD etc/php-xdebug.ini /usr/local/etc/php/conf.d/zz-xdebug-settings.ini

###########################################################################
# Install Postfix
###########################################################################

RUN apt-get update \
    && echo "postfix postfix/mailname string dockerized.site" | debconf-set-selections \
    && echo "postfix postfix/main_mailer_type string 'Internet Site'" | debconf-set-selections \
    && apt-get install -y  \
        postfix \
        libsasl2-modules \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*
COPY etc/postfix/* /etc/postfix/
RUN chmod u=rw,g=r,o=r /etc/postfix/config-*.cf \
    && sed -i "s/relayhost =[ ]*$//g" /etc/postfix/main.cf

###########################################################################
# Configuring...
###########################################################################

ENV PHP_MEMORY_LIMIT=2G \
    PHP_ENABLE_XDEBUG=false \
    MAGENTO_ROOT=/var/www/magento \
    DEBUG=false \
    UPDATE_UID_GID=false

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN ["chmod", "+x", "/docker-entrypoint.sh"]

ENTRYPOINT ["/docker-entrypoint.sh"]
