services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: true

  DockerBuilder\Core\:
    resource: '../src/*'
    exclude: '../src/{Entity,Exception,Contract}'

  DockerBuilder\Core\Config\ConfigGeneratorInterface: '@DockerBuilder\Core\Config\ConfigGenerator'
  DockerBuilder\Core\Config\ConfigLoaderInterface: '@DockerBuilder\Core\Config\JsonConfigLoader'
  DockerBuilder\Core\Config\ConfigValidatorInterface: '@DockerBuilder\Core\Config\ConfigValidator'
  DockerBuilder\Core\File\FileManagerInterface: '@DockerBuilder\Core\File\FileManager'
  DockerBuilder\Core\Template\TemplateRendererInterface: '@DockerBuilder\Core\Template\TemplateRenderer'
  DockerBuilder\Core\Logger\LoggerInterface: '@DockerBuilder\Core\Logger\ConsoleLogger'
#  DockerBuilder\Core\Logger\LoggerInterface:
#    class: DockerBuilder\Logger\ConsoleLogger
#    shared: true

  DockerBuilder\Core\Builder\ConfigBuilderFactory: ~

  DockerBuilder\Core\Console\Command\BuildCommand:
    tags: ['console.command']
