#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM <?= $ELASTICSEARCH_IMAGE . PHP_EOL ?>

MAINTAINER AndriynomeD <andriynomed.work@gmail.com>

RUN elasticsearch-plugin install analysis-phonetic
RUN elasticsearch-plugin install analysis-icu
