#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM <?= $OPENSEARCH_IMAGE . PHP_EOL ?>

MAINTAINER AndriynomeD <andriynomed.work@gmail.com>

RUN opensearch-plugin install analysis-phonetic
RUN opensearch-plugin install analysis-icu
