<?php

declare(strict_types=1);

namespace DockerBuilder\Core\Template;

use Exception;

/**
 * Template Renderer
 */
class TemplateRenderer implements TemplateRendererInterface
{
    private string $templatesPath;

    public function setTemplatesPath(string $templatesPath): void
    {
        $this->templatesPath = $templatesPath . DIRECTORY_SEPARATOR;
    }

    /**
     * @inheirtDoc
     */
    public function render(string $templateFilePath, array $variables): string
    {
        if ($variables['_enable_variables'] ?? false) {
            $content = $this->renderTemplate($templateFilePath, $variables);
        } else {
            $content = $this->renderWithoutTemplate($templateFilePath);
        }

        return $content;
    }

    /**
     * Render the given template file using the provided variables and return the resulting output.
     *
     * @param string $templateFilePath
     * @param array $variables
     * @return string
     */
    protected function renderTemplate(string $templateFilePath, array $variables): string
    {
        extract($variables, EXTR_OVERWRITE);
        ob_start();
        include $this->templatesPath . $templateFilePath;
        $output = ob_get_clean() ?: "";
        $output = str_replace('{{generated_by_builder}}',
            'This file is automatically generated. Do not edit directly.', $output);
        return $output;
    }

    /**
     * @param string $templateFilePath
     * @return string
     * @throws Exception
     */
    protected function renderWithoutTemplate(string $templateFilePath): string
    {
        $output = file_get_contents($this->templatesPath . $templateFilePath);
        if ($output === false) {
            throw new Exception(sprintf("Failed to read template file %s", $templateFilePath));
        }
        $output = str_replace('{{generated_by_builder}}',
            'This file is automatically generated. Do not edit directly.', $output);
        return $output;
    }

    /**
     * @inheirtDoc
     */
    public function findTemplate(string $filename, array $config): ?string
    {
        foreach (['templateSubDir', 'version', 'flavour', 'template_infix', 'template_name'] as $key) {
            $config[$key] = $config[$key] ?? '';
        }

        $templateSubDir = $config['templateSubDir'];
        $potentialFilenames = $this->getPotentialFilenames($filename, $config);;
        foreach ($potentialFilenames as $potentialFilename) {
            $path = $templateSubDir . $potentialFilename;
            /* Old template & normal files check */
            $testPath = $this->templatesPath . $path;
            if (file_exists($testPath)) {
                if (!is_readable($testPath)) {
                    throw new Exception(sprintf('Template file %s not readable.', $testPath));
                }
                return $path;
            }
        }

        return null;
    }

    /**
     * Example for 'Dockerfile' + ['template_name' => 'Dockerfile.tml']:
     *    [
     *       'Dockerfile.tml' - will be found
     *    ]
     * Example for 'Dockerfile' + ['version' => '7.4', 'flavour' => 'cli']:
     *   [
     *      'Dockerfile-7.4-cli'
     *      'Dockerfile-7.4'
     *      'Dockerfile-cli' - will be found
     *      'Dockerfile'
     *   ]
     * Example for 'Dockerfile' + ['version' => '7.4', 'flavour' => 'cli', 'template_infix' => 'mcs']:
     *    [
     *      'Dockerfile-7.4-mcs-cli'
     *      'Dockerfile-7.4-mcs'
     *      'Dockerfile-mcs-cli' - will be found
     *      'Dockerfile-mcs'
     *      'Dockerfile-7.4-cli'
     *      'Dockerfile-7.4'
     *      'Dockerfile-cli'
     *      'Dockerfile'
     *    ]
     *
     * @param string $filename
     * @param array $config
     * @return array
     */
    private function getPotentialFilenames(string $filename, array $config): array
    {
        if (!!$config['template_name']) {
            return [$config['template_name']];
        }

        $potentialFilenames = [
            sprintf("%s-%s-%s", $filename, $config['version'], $config['flavour']),
            sprintf("%s-%s", $filename, $config['version']),
            sprintf("%s-%s", $filename, $config['flavour']),
            $filename,
        ];

        if (!$config['template_infix']) {
            return $potentialFilenames;
        }

        return [
            sprintf("%s-%s-%s-%s", $filename, $config['version'], $config['template_infix'], $config['flavour']),
            sprintf("%s-%s-%s", $filename, $config['version'], $config['template_infix']),
            sprintf("%s-%s-%s", $filename, $config['template_infix'], $config['flavour']),
            sprintf("%s-%s", $filename, $config['template_infix']),
            ...$potentialFilenames
        ];
    }
}
