{% set flavourPackages = [
    'cron',
    'rsyslog',
    'iproute2'
] %}

{% if databaseType == 'mysql' or databaseType == 'percona' %}
    {% set flavourPackages = flavourPackages|merge([
        version_compare(databaseVersion, '7.0', '<=') ? 'mysql-client' : 'default-mysql-client'
    ]) %}
{% elseif databaseType == 'mariadb' or databaseType is not defined %}
    {% set flavourPackages = flavourPackages|merge(['mariadb-client']) %}
{% endif %}

{% include "phpContainers/php-mcs/includes/dockerfile-head.twig" %}

{% if specificPackages.grunt is defined and specificPackages.grunt != false %}
###########################################################################
# Install Grunt
###########################################################################

RUN apt-get update \
    && apt-get install -y \
    curl gnupg && curl -sL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs && npm install -g grunt-cli \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

{% endif %}
###########################################################################
# Configuring...
###########################################################################

ENV COMPOSER_ALLOW_SUPERUSER=1 \
    COMPOSER_GITHUB_TOKEN="" \
    COMPOSER_MAGENTO_USERNAME="" \
    COMPOSER_MAGENTO_PASSWORD="" \
    COMPOSER_BITBUCKET_KEY="" \
    COMPOSER_BITBUCKET_SECRET=""

VOLUME /root/.composer/cache

COPY etc/php-cli.ini /usr/local/etc/php/conf.d/zz-magento.ini

###########################################################################
# Get composer installed to /usr/local/bin/composer
###########################################################################
{% set composerVersionFlag = (composerVersion == 'latest' or composerVersion == '') ? '' : '--version=' ~ composerVersion %}
RUN curl -sS https://getcomposer.org/installer | php -- --install-dir=/usr/local/bin --filename=composer {{ composerVersionFlag }}

###########################################################################
# Final Configuring
###########################################################################

COPY bin/* /usr/local/bin/
RUN ["chmod", "+x", "/usr/local/bin/magento-coding-standard-installer"]

WORKDIR $MCS_ROOT

CMD ["bash"]
