#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM php:{{ phpVersion }}-{{ flavour }}

LABEL maintainer="AndriynomeD <andriynomed.work@gmail.com>"

{% set parts = phpVersion|split('.') %}
{% set shortVersion = parts[0] ~ '.' ~ parts[1] %}
ARG PHP_VERSION={{ shortVersion }}

{% set flavourPackages = [
    'cron',
    'rsyslog',
    'iproute2',
    'procps',
    'htop'
] %}
{%- if databaseType == 'mysql' or databaseType == 'percona' %}
    {%- if version_compare(databaseVersion, '7.0', '<=') %}
        {%- set flavourPackages = flavourPackages|merge(['mysql-client']) %}
    {%- else %}
        {%- set flavourPackages = flavourPackages|merge(['default-mysql-client']) %}
    {%- endif %}
{%- else %}
    {%- set flavourPackages = flavourPackages|merge(['mariadb-client']) %}
{%- endif %}
{% include "phpContainers/includes/base-system-deps.twig" %}
{% include "phpContainers/includes/base-php-extensions.twig" %}
{% include "phpContainers/includes/zip.twig" %}
{% set specificPackages = specificPackages|merge({'grunt': true}) %}
{% include "phpContainers/php-cli/includes/specific-packages-grunt.twig" %}
{% include "phpContainers/php-cli/includes/composer.twig" %}
{#{% include "phpContainers/includes/mail-service.twig" %}#}
{#{% include "phpContainers/includes/xdebug.twig" %}#}
{% include "phpContainers/includes/version-specific-system-deps.twig" %}
{% include "phpContainers/includes/version-specific-php-extensions.twig" %}
{#{% include "phpContainers/includes/specific-packages-gd.twig" %}#}
{#{% include "phpContainers/includes/specific-packages-imagick.twig" %}#}
{#{% include "phpContainers/includes/specific-packages-ssh2.twig" %}#}
{#{% include "phpContainers/includes/specific-packages-ioncube.twig" %}#}
{#{% include "phpContainers/includes/specific-packages-cloud.twig" %}#}
###########################################################################
# Final Configuring
###########################################################################

ENV PHP_MEMORY_LIMIT=4G \
    PHP_ENABLE_XDEBUG=false \
    APP_ROOT=/var/www/html \
    DEBUG=false \
    UPDATE_UID_GID=false

COPY etc/php-cli.ini /usr/local/etc/php/conf.d/zz-magento.ini

COPY bin/* /usr/local/bin/
COPY docker-entrypoint.sh /usr/local/bin/docker-entrypoint.sh
RUN chmod +x /usr/local/bin/docker-entrypoint.sh

#RUN find /usr/local/bin -type f -exec chmod +x {} +
RUN for file in \
        /usr/local/bin/magento-coding-standard-installer; \
    do \
        chmod +x "$file"; \
    done

WORKDIR $APP_ROOT

ENTRYPOINT ["docker-entrypoint.sh"]

CMD ["bash"]
