#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM opensearchproject/opensearch:<?= $OPENSEARCH_VERSION . PHP_EOL ?>

LABEL maintainer="AndriynomeD <andriynomed.work@gmail.com>"

RUN opensearch-plugin install analysis-phonetic
RUN opensearch-plugin install analysis-icu
