#
#--------------------------------------------------------------------------
# {{ generated_by_builder }}
#--------------------------------------------------------------------------

FROM opensearchproject/opensearch:{{ OPENSEARCH_VERSION }}

LABEL maintainer="AndriynomeD <andriynomed.work@gmail.com>"

RUN opensearch-plugin install analysis-phonetic
RUN opensearch-plugin install analysis-icu
