#
#--------------------------------------------------------------------------
# {{generated_by_builder}}
#--------------------------------------------------------------------------

FROM php:{{ phpVersion }}-{{ flavour }}

LABEL maintainer="AndriynomeD <andriynomed.work@gmail.com>"

{% set phpVersionParts = phpVersion|split('.') %}
{% set shortVersion = phpVersionParts[0] ~ '.' ~ phpVersionParts[1] %}
ARG PHP_VERSION={{ shortVersion }}

###########################################################################
# Install dependencies
###########################################################################
{% set imagePackages = [
    'libicu-dev',
    'libfreetype6-dev',
    'libjpeg62-turbo-dev',
    'libpng-dev',
    'libmcrypt-dev',
    'libxslt1-dev',
    'libzip-dev',
    'sudo',
    'git'
]|merge(packages|default([]))|merge(flavourPackages|default([])) %}

RUN apt-get update \
  && apt-get install -y \
    {{ imagePackages|join(" \\ \n    ") }} \
  && apt-get clean \
  && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

###########################################################################
# Install required PHP extensions
###########################################################################
{% set imagePhpExtensions = [
  'dom',
  'intl',
  'mbstring',
  'pdo_mysql',
  'xsl',
  'soap',
  'bcmath',
  'pcntl',
  'sockets'
]|merge(phpExtensions|default([]))|merge(flavourPhpExtensions|default([])) %}

RUN docker-php-ext-install -j$(nproc) \
  {{ imagePhpExtensions|join(" \\ \n  ") }} \
    && docker-php-source delete

###########################################################################
# Zip/Unzip (copy from https://github.com/laradock/laradock/blob/master/php-fpm/Dockerfile):
###########################################################################

RUN apt-get update \
  && apt-get install -y \
    libzip-dev zip unzip && \
    if [ ${PHP_VERSION} = "7.3" ] || [ ${PHP_VERSION} = "7.4" ] || [ $(php -r "echo PHP_MAJOR_VERSION;") = "8" ]; then \
      docker-php-ext-configure zip; \
    else \
      docker-php-ext-configure zip --with-libzip; \
    fi && \
    # Install the zip extension
    docker-php-ext-install zip && \
    php -m | grep -q 'zip' \
    && docker-php-source delete \
    && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/*

{% include "phpContainers/includes/specific-packages.twig" %}
###########################################################################
# Configuring...
###########################################################################

ENV PHP_MEMORY_LIMIT=4G \
    PHP_ENABLE_XDEBUG=false \
    APP_ROOT=/var/www/html \
    DEBUG=false \
    UPDATE_UID_GID=false

COPY docker-entrypoint.sh /docker-entrypoint.sh
RUN ["chmod", "+x", "/docker-entrypoint.sh"]

ENTRYPOINT ["/docker-entrypoint.sh"]
