#
#--------------------------------------------------------------------------
# {{ generated_by_builder }}
#--------------------------------------------------------------------------

FROM {{ IMAGE }}:{{ TAG }}

LABEL maintainer="AndriynomeD <andriynomed.work@gmail.com>"

RUN opensearch-plugin install analysis-phonetic
RUN opensearch-plugin install analysis-icu
